name: Android CI (Kotlin)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # 1. JAVA SETUP
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    
    # 2. ANDROID SDK SETUP
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    # 3. LICENSE ACCEPTANCE
    - name: Accept Android licenses
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
        
    # 4. GRADLE PERMISSIONS
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    # 5. GRADLE CACHING
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-
          
    # 6. VERIFY KOTLIN (optional diagnostic)
    - name: Check Kotlin version
      run: ./gradlew -q kotlinVersion
      
    # 7. BUILD & TEST
    - name: Build and test
      env:
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx2048m"
      run: |
        ./gradlew clean build test --stacktrace
        
    # 8. ARTIFACT UPLOAD
    - name: Upload APK artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: |
          app/build/outputs/apk/**/*.apk
          app/build/outputs/bundle/**/*.aab
        retention-days: 7
        
    # 9. LINT CHECK
    - name: Run lint
      run: ./gradlew lint
