#!/usr/bin/env sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# ATTENTION: This script is generated by the Gradle wrapper. 
#            Do not modify this script directly.
#            Instead, you should modify the wrapper configuration and run ./gradlew --refresh-dependencies

# Set environment variables for the Gradle wrapper.

# Determine the directory where the script resides
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)

# Use the maximum available memory for the Gradle daemon by default.
# To specify a maximum memory setting, uncomment the following line:
# GRADLE_OPTS="-Xmx1024m $GRADLE_OPTS"

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Set the application name used by the Gradle wrapper
APP_NAME="Gradle"

# Set the application home directory.
APP_HOME="$SCRIPT_DIR"

# Set the classpath
CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME\n\nPlease set the JAVA_HOME variable in your environment to match the\nlocation of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.\n\nPlease set the JAVA_HOME variable in your environment to match the\nlocation of your Java installation."
fi

# Increase the maximum heap size for the Gradle daemon
if [ -z "$GRADLE_OPTS" ]; then
    GRADLE_OPTS="-Xmx512m"
fi

# Escape application args
escaped_args=""
for arg in "$@"; do
    escaped_arg=$(printf '%s\n' "$arg" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')
    escaped_args="$escaped_args \"$escaped_arg\""
done

# Split up the JVM options only if DEFAULT_JVM_OPTS is specified
if [ -n "$DEFAULT_JVM_OPTS" ]; then
    eval "set -- $DEFAULT_JVM_OPTS"
    JVM_OPTS=""
    for opt in "$@"; do
        JVM_OPTS="$JVM_OPTS \"$opt\""
    done
else
    JVM_OPTS=""
fi

# Execute Gradle
exec "$JAVACMD" $JVM_OPTS $GRADLE_OPTS "-Dorg.gradle.appname=$APP_NAME" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain $escaped_args

